title: Marco Valente - Web Application Developer
email: MarcoValente@gmail.com
description: I'm a web application developer who builds web applications with Python, PHP, JavaScript and many other useful tools.

# Social
linkedin_username: MarcoV4lente
github_username:  MarcoV4lente
instagram_username:  MarcoV4lente

# paths
baseurl: '/'
url: 'https://marcovalente.io/'
permalink: '/articles/:title/'

# Pagination
pagination:
    enabled: true
    debug: false
    collection: 'posts'
    per_page: 5
    permalink: '/:num/' # Pages are index.html inside this folder (default)
    #permalink: '/page/:num.html' # Pages are simple html files
    #permalink: '/page/:num' # Pages are html files, linked jekyll extensionless permalink style.
    title: ':title - page :num'
    limit: 0
    sort_field: 'date'
    sort_reverse: true
    category: 'posts'
    tag: ''
    locale: ''
    trail:
        before: 2
        after: 2

# sass
sass:
    sass_dir: _sass
    style: compressed

# Build settings
source: .
destination: _site

markdown: kramdown
# theme: minima

gems:
    - jekyll-feed
    - jekyll-paginate-v2
exclude:
    - node_modules
    - .gitignore
    - Gemfile
    - Gemfile.lock
    - gulpfile.js
    - package.json
