# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# Variables
title: MarcoV4lente - Web Application Developer
email: marcov4lente@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hi, I'm Marco! I'm a web application developer! Web technologies fascinate me, and I find pleasure in conceptualising and building functional web applications that serve purpose.
baseurl: ""
url: "https://marcov4lente.com"
linkedin_username: marcov4lente
github_username:  marcov4lente
instagram_username:  marcov4lente

permalink: /articles/:title/

# Pagination
paginate: 5
paginate_path: "/articles/page:num/"

# sass
sass:
    sass_dir: _sass
    style: compressed

# Build settings
source: .
destination: _site

markdown: kramdown
# theme: minima

gems:
    - jekyll-feed
    - jekyll-paginate
exclude:
    - node_modules
    - .gitignore
    - Gemfile
    - Gemfile.lock
    - gulpfile.js
    - package.json
